name: mega_show
description: movies database applications

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.1.0
  ## for photo sliding!!
  carousel_slider: ^4.0.0
  slide_drawer: ^1.0.3
  hexcolor: ^2.0.4
  http: ^0.13.3
  fluttertoast: ^8.0.8
  webview_flutter: ^2.0.12





dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/fonts/monte_carlo/MonteCarlo-Regular.ttf
    - assets/fonts/monte_carlo/OFL.txt
    - assets/images/
  fonts:
    - family: MonteCarlo
      fonts:
        - asset: assets/fonts/monte_carlo/MonteCarlo-Regular.ttf
  #     - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
