/// Generated by AssetsRefGenerator on 2021/08/05
class Res {
  static const String MonteCarlo_Regular = "assets/fonts/monte_carlo/MonteCarlo-Regular.ttf";
  static const String OFL = "assets/fonts/monte_carlo/OFL.txt";
}
